# Rental Dataset

Using a dataset from streeteast containing the rental information for 5000 NYC apartments, I will be conducting EDA on the data to see what further information we can find out from this data. From my limited knowledge about NYC, the apartments are more expensive in areas such as Manhattan and Brooklyn and as you move further out, it gets cheaper, for example rental listings in Staten Island will generally be cheaper than those in the Upper East Side.  

The data for this analysis is from streeteasy provided by codecademy as part of their statistics with python YouTube series. 

## Import Relevant Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# printing out the version of pandas used for this analysis
print(pd.__version__)

1.2.1


## Get Data

In [3]:
rental_df = pd.read_csv("https://raw.githubusercontent.com/Codecademy/datasets/master/streeteasy/streeteasy.csv")

## Get a feel for the data

In [4]:
rental_df.head()

rental_id  building_id   rent  bedrooms  bathrooms  size_sqft  \
0       1545     44518357   2550       0.0          1        480   
1       2472     94441623  11500       2.0          2       2000   
2      10234     87632265   3000       3.0          1       1000   
3       2919     76909719   4500       1.0          1        916   
4       2790     92953520   4795       1.0          1        975   

   min_to_subway  floor  building_age_yrs  no_fee  has_roofdeck  \
0              9    2.0                17       1             1   
1              4    1.0                96       0             0   
2              4    1.0               106       0             0   
3              2   51.0                29       0             1   
4              3    8.0                31       0             0   

   has_washer_dryer  has_doorman  has_elevator  has_dishwasher  has_patio  \
0                 0            0             1               1          0   
1                 0            0             0               0          0   
2                 0            0             0               0          0   
3                 0            1             1               1          0   
4                 0            1             1               1          0   

   has_gym       neighborhood            submarket    borough  
0        1    Upper East Side  All Upper East Side  Manhattan  
1        0  Greenwich Village         All Downtown  Manhattan  
2        0            Astoria     Northwest Queens     Queens  
3        0            Midtown          All Midtown  Manhattan  
4        1  Greenwich Village         All Downtown  Manhattan

In [5]:
rental_df.tail()

rental_id  building_id  rent  bedrooms  bathrooms  size_sqft  \
4995       1964     73060494  2650       1.0          1        686   
4996       5686     92994390  6675       2.0          2        988   
4997       9679      7689663  1699       0.0          1        250   
4998       5188     62828354  3475       1.0          1        651   
4999       4718     67659586  4500       1.0          1        816   

      min_to_subway  floor  building_age_yrs  no_fee  has_roofdeck  \
4995              9    4.0                 3       1             0   
4996              5   10.0                 9       1             1   
4997              2    5.0                96       0             0   
4998              6    5.0                14       1             0   
4999              4   11.0                 9       0             1   

      has_washer_dryer  has_doorman  has_elevator  has_dishwasher  has_patio  \
4995                 0            0             0               0          0   
4996                 1            1             1               1          0   
4997                 0            0             0               0          0   
4998                 1            1             1               1          0   
4999                 1            1             1               0          1   

      has_gym  neighborhood         submarket    borough  
4995        0       Astoria  Northwest Queens     Queens  
4996        1       Tribeca      All Downtown  Manhattan  
4997        0  Little Italy      All Downtown  Manhattan  
4998        1  Midtown West       All Midtown  Manhattan  
4999        1       Tribeca      All Downtown  Manhattan

In [6]:
rental_df.sample(5)

rental_id  building_id  rent  bedrooms  bathrooms  size_sqft  \
107        8385      8217653  2695       1.0          1        875   
2435       2408     95698673  6000       1.0          1        750   
231        3136     53659992  4050       1.0          1        805   
4115        122     66925959  6900       1.0          1       1000   
2774       2665     89295017  1949       0.0          1        400   

      min_to_subway  floor  building_age_yrs  no_fee  has_roofdeck  \
107               8   15.0                56       1             0   
2435              5    4.0               106       0             0   
231              11   20.0                15       1             0   
4115              1    2.0               109       0             0   
2774              6    1.0                96       0             0   

      has_washer_dryer  has_doorman  has_elevator  has_dishwasher  has_patio  \
107                  0            0             0               0          0   
2435                 1            0             0               1          0   
231                  0            0             0               0          0   
4115                 0            0             0               0          0   
2774                 0            0             1               0          0   

      has_gym     neighborhood            submarket    borough  
107         0     Forest Hills       Central Queens     Queens  
2435        0     West Village         All Downtown  Manhattan  
231         0  Upper East Side  All Upper East Side  Manhattan  
4115        0     West Village         All Downtown  Manhattan  
2774        0     East Village         All Downtown  Manhattan

This NYC rental data from streeteasy did not come with a README file or a document explaining the various columns, though most of the information is straightforward and can be easily looked up therefore a lack of background knowledge should not be an issue in conducting this analysis. 

From what I can see above (by viewing the top 5 rows, bottom 5 rows and a random sample of 5 rows from within the dataframe) the data seems to be structured and organized. A number of the columns such as `has_doorman`, `no_fee`,  and `has_gym` the values have been encoded using a one hot encoding scheme, this created a binary column for all these categories/features. With this in mind, one can assume that 1 = yes and 0 = no, using boolean logic of True = 1 and False = 0

In [7]:
rental_df.shape

(5000, 20)

In [8]:
list(rental_df.columns)

['rental_id',
 'building_id',
 'rent',
 'bedrooms',
 'bathrooms',
 'size_sqft',
 'min_to_subway',
 'floor',
 'building_age_yrs',
 'no_fee',
 'has_roofdeck',
 'has_washer_dryer',
 'has_doorman',
 'has_elevator',
 'has_dishwasher',
 'has_patio',
 'has_gym',
 'neighborhood',
 'submarket',
 'borough']

This dataframe contains information about 5000 rental units, along with 20 columns. 

In [9]:
rental_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   rental_id         5000 non-null   int64  
 1   building_id       5000 non-null   int64  
 2   rent              5000 non-null   int64  
 3   bedrooms          5000 non-null   float64
 4   bathrooms         5000 non-null   int64  
 5   size_sqft         5000 non-null   int64  
 6   min_to_subway     5000 non-null   int64  
 7   floor             5000 non-null   float64
 8   building_age_yrs  5000 non-null   int64  
 9   no_fee            5000 non-null   int64  
 10  has_roofdeck      5000 non-null   int64  
 11  has_washer_dryer  5000 non-null   int64  
 12  has_doorman       5000 non-null   int64  
 13  has_elevator      5000 non-null   int64  
 14  has_dishwasher    5000 non-null   int64  
 15  has_patio         5000 non-null   int64  
 16  has_gym           5000 non-null   int64  


As we can see from the cell above, the dataframe has no missing values (though I'll be verifying that later), and all of the binary columns are being read by pandas as integer values.

## Binary Columns 

The columns encoded using a one-hot encoding scheme (or the columns with binary values) will be changed to `yes` and `no` in order to make the analysis a bit easier and to ensure that their type changes to a string value (object)

Just by looking at the top 5 rows in the dataframe, I would be able to tell which columns are binary and which aren't but just for my sanity and for simplicity I will be going through the unique values in all 20 columns in order to determine which are binary 

In [10]:
rental_df.columns

Index(['rental_id', 'building_id', 'rent', 'bedrooms', 'bathrooms',
       'size_sqft', 'min_to_subway', 'floor', 'building_age_yrs', 'no_fee',
       'has_roofdeck', 'has_washer_dryer', 'has_doorman', 'has_elevator',
       'has_dishwasher', 'has_patio', 'has_gym', 'neighborhood', 'submarket',
       'borough'],
      dtype='object')

In [11]:
print(rental_df.rental_id.nunique())
print(rental_df.rental_id.unique())

5000
[ 1545  2472 10234 ...  9679  5188  4718]


In [12]:
print(rental_df.building_id.nunique())
print(rental_df.building_id.unique())

2315
[44518357 94441623 87632265 ... 86914672 20773991 35251179]


In [13]:
print(rental_df.rent.nunique())
print(rental_df.rent.unique())

1016
[ 2550 11500  3000 ...  6755  4210  6675]


In [14]:
print(rental_df.bedrooms.nunique())
print(rental_df.bedrooms.unique())

11
[0.  2.  3.  1.  0.5 2.5 4.  5.  1.5 3.5 4.5]


In [15]:
print(rental_df.bathrooms.nunique())
print(rental_df.bathrooms.unique())

6
[1 2 0 3 4 5]


In [16]:
print(rental_df.size_sqft.nunique())
print(rental_df.size_sqft.unique())

1113
[ 480 2000 1000 ... 1193 2470  816]


In [17]:
print(rental_df.min_to_subway.nunique())
print(rental_df.min_to_subway.unique())

24
[ 9  4  2  3  1  6  0  5 43  7 10 11 12  8 13 14 27 18 15 16 17 37 20 51]


In [18]:
print(rental_df.floor.nunique())
print(rental_df.floor.unique())

67
[ 2.   1.  51.   8.   3.   4.   7.   5.   9.  21.  30.  17.  14.  40.
 15.  12.  22.  26.   6.  19.  46.  24.  36.  10.  27.  25.  11.  16.
 28.  29.  38.  18.  43.  34.  23.  13.  32.  20.  33.  37.  55.  35.
  1.5 45.  58.  54.  31.  39.  53.  41.  42.  50.  47.  56.  83.  44.
 66.  64.  68.  81.  48.  52.  62.  49.   0.  57.   6.5]


In [19]:
print(rental_df.building_age_yrs.nunique())
print(rental_df.building_age_yrs.unique())

130
[ 17  96 106  29  31  15  83 136   3 101   8 115  33   2  14  88  39  52
  11  89  85 111   7  20  10   9  56  65  44   5  27   6 116  75  13  87
  57  91 105  16  86  30 112  25  47  28  90  42  43   0  66 102  76  58
 113  37   4  60  32  54 109 151  61  12 126  41   1  38  92  19  62  71
  55  53  80 100  93  99  51  64  68 108 132  34 107  46  18  98 117  84
  26  81  79  94 103  21  50 110  59  22  95 180  63 104  24  36  48 118
  69  35 157 156 124 114  45 122 120  70  78 121 143  77  74  49  67 146
  40  82 131 174]


In [20]:
print(rental_df.no_fee.nunique())
print(rental_df.no_fee.unique())

2
[1 0]


In [21]:
print(rental_df.has_roofdeck.nunique())
print(rental_df.has_roofdeck.unique())

2
[1 0]


In [22]:
print(rental_df.has_washer_dryer.nunique())
print(rental_df.has_washer_dryer.unique())

2
[0 1]


In [23]:
print(rental_df.has_doorman.nunique())
print(rental_df.has_doorman.unique())

2
[0 1]


In [24]:
print(rental_df.has_elevator.nunique())
print(rental_df.has_elevator.unique())

2
[1 0]


In [25]:
print(rental_df.has_dishwasher.nunique())
print(rental_df.has_dishwasher.unique())

2
[1 0]


In [26]:
print(rental_df.has_patio.nunique())
print(rental_df.has_patio.unique())

2
[0 1]


In [27]:
print(rental_df.has_gym.nunique())
print(rental_df.has_gym.unique())

2
[1 0]


In [28]:
print(rental_df.neighborhood.nunique())
print(rental_df.neighborhood.unique())

93
['Upper East Side' 'Greenwich Village' 'Astoria' 'Midtown' 'Williamsburg'
 'Forest Hills' 'Soho' 'Central Harlem' 'Greenwood' 'Midtown East'
 'Battery Park City' 'Gowanus' 'Flatiron' 'Brooklyn Heights'
 'East Village' 'Midtown West' 'Upper West Side' 'Briarwood'
 'Lower East Side' 'Tribeca' 'Clinton Hill' 'Gramercy Park' 'Rego Park'
 'East Harlem' 'Boerum Hill' 'Park Slope' 'West Village' 'Sheepshead Bay'
 'Central Park South' 'Long Island City' 'Chelsea' 'Financial District'
 'Inwood' 'Carroll Gardens' 'Midtown South' 'Red Hook' 'Fort Greene'
 'Washington Heights' 'Downtown Brooklyn' 'Crown Heights' 'Chinatown'
 'Sunnyside' 'Prospect Park South' 'Roosevelt Island'
 'Columbia St Waterfront District' 'Jackson Heights' 'Greenpoint'
 'Hamilton Heights' 'Kensington' 'Bushwick' 'Kew Gardens' 'Elmhurst'
 'Brighton Beach' 'Kew Gardens Hills' 'Corona' 'Prospect Heights'
 'Stuyvesant Town/PCV' 'Richmond Hill' 'Bedford-Stuyvesant' 'Bay Ridge'
 'Flatbush' 'DUMBO' 'Jamaica Estates' 'Brownsville

In [29]:
print(rental_df.submarket.nunique())
print(rental_df.submarket.unique())

15
['All Upper East Side' 'All Downtown' 'Northwest Queens' 'All Midtown'
 'North Brooklyn' 'Central Queens' 'All Upper Manhattan' 'South Brooklyn'
 'Northwest Brooklyn' 'All Upper West Side' 'Northeast Queens'
 'Prospect Park' 'East Brooklyn' 'South Queens' 'The Rockaways']


In [30]:
print(rental_df.borough.nunique())
print(rental_df.borough.unique())

3
['Manhattan' 'Queens' 'Brooklyn']


There are 8 binary columns and the next cell will see a change in their values from 1/0 to yes/no

In [31]:
# visualizing the binary columns before changing them
rental_df.sample(10)

rental_id  building_id  rent  bedrooms  bathrooms  size_sqft  \
3696       2712     99185963  4800       2.0          2       1200   
3888       8072     26998106  4850       1.0          1        675   
2943       4582     69339033  3800       1.0          1        880   
3212       1666     29790601  2950       1.0          1        737   
3907       4763     69837186  3810       1.0          1        707   
2395       4024     93270979  2899       2.0          1        750   
1523       9269     71977815  3900       1.0          1        640   
3451       3509     66540513  3400       1.0          1        721   
3245       5321     79832606  4200       2.0          1       1000   
2515       8190     24990628  4175       1.0          1        713   

      min_to_subway  floor  building_age_yrs  no_fee  has_roofdeck  \
3696              2    4.0                30       0             0   
3888              2   21.0                42       1             0   
2943              7   18.0                16       0             0   
3212              7    3.0                12       0             0   
3907              4   12.0                28       1             0   
2395              4    4.0                 9       0             0   
1523              4    8.0                 7       1             0   
3451              7   11.0                12       0             0   
3245              0    3.0                96       0             1   
2515              4    9.0                19       1             1   

      has_washer_dryer  has_doorman  has_elevator  has_dishwasher  has_patio  \
3696                 0            1             1               1          0   
3888                 0            0             0               0          0   
2943                 0            0             0               0          0   
3212                 0            0             1               0          0   
3907                 0            0             0               0          0   
2395                 0            0             0               0          0   
1523                 0            0             0               0          0   
3451                 0            1             1               0          0   
3245                 1            1             1               0          0   
2515                 1            1             1               0          0   

      has_gym      neighborhood            submarket    borough  
3696        0   Upper West Side  All Upper West Side  Manhattan  
3888        0   Upper West Side  All Upper West Side  Manhattan  
2943        0   Upper West Side  All Upper West Side  Manhattan  
3212        0  Roosevelt Island  All Upper East Side  Manhattan  
3907        0   Upper West Side  All Upper West Side  Manhattan  
2395        0      Williamsburg       North Brooklyn   Brooklyn  
1523        0           Tribeca         All Downtown  Manhattan  
3451        0   Upper West Side  All Upper West Side  Manhattan  
3245        0   Upper East Side  All Upper East Side  Manhattan  
2515        1   Upper East Side  All Upper East Side  Manhattan

In [32]:
rental_df['no_fee'] = rental_df['no_fee'].map({1:"yes", 0:"no"})

In [33]:
rental_df['has_roofdeck'] = rental_df['has_roofdeck'].map({1:"yes", 0:"no"})

In [34]:
rental_df['has_washer_dryer'] = rental_df['has_washer_dryer'].map({1:"yes", 0:"no"})

In [35]:
rental_df['has_doorman'] = rental_df['has_doorman'].map({1:"yes", 0:"no"})

In [36]:
rental_df['has_elevator'] = rental_df['has_elevator'].map({1:"yes", 0:"no"})

In [37]:
rental_df['has_dishwasher'] = rental_df['has_dishwasher'].map({1:"yes", 0:"no"})

In [38]:
rental_df['has_patio'] = rental_df['has_patio'].map({1:"yes", 0:"no"})

In [39]:
rental_df['has_gym'] = rental_df['has_gym'].map({1:"yes", 0:"no"})

As a way to check that the cells above ran without any issues, I'll be calling the `.head()`, `.sample()`, and `.tail()` functions again.

In [40]:
rental_df.head()

rental_id  building_id   rent  bedrooms  bathrooms  size_sqft  \
0       1545     44518357   2550       0.0          1        480   
1       2472     94441623  11500       2.0          2       2000   
2      10234     87632265   3000       3.0          1       1000   
3       2919     76909719   4500       1.0          1        916   
4       2790     92953520   4795       1.0          1        975   

   min_to_subway  floor  building_age_yrs no_fee has_roofdeck  \
0              9    2.0                17    yes          yes   
1              4    1.0                96     no           no   
2              4    1.0               106     no           no   
3              2   51.0                29     no          yes   
4              3    8.0                31     no           no   

  has_washer_dryer has_doorman has_elevator has_dishwasher has_patio has_gym  \
0               no          no          yes            yes        no     yes   
1               no          no           no             no        no      no   
2               no          no           no             no        no      no   
3               no         yes          yes            yes        no      no   
4               no         yes          yes            yes        no     yes   

        neighborhood            submarket    borough  
0    Upper East Side  All Upper East Side  Manhattan  
1  Greenwich Village         All Downtown  Manhattan  
2            Astoria     Northwest Queens     Queens  
3            Midtown          All Midtown  Manhattan  
4  Greenwich Village         All Downtown  Manhattan

In [41]:
rental_df.sample(10)

rental_id  building_id   rent  bedrooms  bathrooms  size_sqft  \
881        6755     47270803  10495       2.0          2       1549   
2210       8856     32178621   4600       1.0          1        960   
2685       7980     26998106   5250       1.0          1        827   
4673       6611     14842171   3500       2.0          1        850   
2259       8999     46651061   2800       1.0          1        700   
3922       6330     61588338   2500       2.0          1       1000   
1884       8715     77022425   2400       0.0          1        444   
1963       6963     41939749   2200       1.0          1        500   
2359       8289     14842171   4350       3.0          1        950   
923         179     61960846   9000       2.0          2       1192   

      min_to_subway  floor  building_age_yrs no_fee has_roofdeck  \
881               4    7.0               115     no           no   
2210              4    6.0                33     no           no   
2685              2   35.0                42    yes           no   
4673              2    1.0               106    yes           no   
2259              7    1.0               101     no           no   
3922             18    2.0                27    yes           no   
1884              8   26.0                29     no          yes   
1963              9    3.0                85     no           no   
2359              2    2.0               106    yes           no   
923               2   11.0                86     no           no   

     has_washer_dryer has_doorman has_elevator has_dishwasher has_patio  \
881                no          no           no             no        no   
2210               no          no           no             no        no   
2685               no          no           no             no        no   
4673               no          no           no             no        no   
2259               no          no           no             no        no   
3922               no          no           no             no        no   
1884               no         yes          yes             no        no   
1963               no          no           no             no        no   
2359               no          no           no             no        no   
923                no          no          yes             no        no   

     has_gym        neighborhood            submarket    borough  
881       no     Upper West Side  All Upper West Side  Manhattan  
2210      no        Midtown East          All Midtown  Manhattan  
2685      no     Upper West Side  All Upper West Side  Manhattan  
4673      no        Williamsburg       North Brooklyn   Brooklyn  
2259      no     Carroll Gardens   Northwest Brooklyn   Brooklyn  
3922      no             Astoria     Northwest Queens     Queens  
1884     yes     Upper East Side  All Upper East Side  Manhattan  
1963      no          Park Slope        Prospect Park   Brooklyn  
2359      no        Williamsburg       North Brooklyn   Brooklyn  
923       no  Central Park South          All Midtown  Manhattan

In [42]:
rental_df.tail()

rental_id  building_id  rent  bedrooms  bathrooms  size_sqft  \
4995       1964     73060494  2650       1.0          1        686   
4996       5686     92994390  6675       2.0          2        988   
4997       9679      7689663  1699       0.0          1        250   
4998       5188     62828354  3475       1.0          1        651   
4999       4718     67659586  4500       1.0          1        816   

      min_to_subway  floor  building_age_yrs no_fee has_roofdeck  \
4995              9    4.0                 3    yes           no   
4996              5   10.0                 9    yes          yes   
4997              2    5.0                96     no           no   
4998              6    5.0                14    yes           no   
4999              4   11.0                 9     no          yes   

     has_washer_dryer has_doorman has_elevator has_dishwasher has_patio  \
4995               no          no           no             no        no   
4996              yes         yes          yes            yes        no   
4997               no          no           no             no        no   
4998              yes         yes          yes            yes        no   
4999              yes         yes          yes             no       yes   

     has_gym  neighborhood         submarket    borough  
4995      no       Astoria  Northwest Queens     Queens  
4996     yes       Tribeca      All Downtown  Manhattan  
4997      no  Little Italy      All Downtown  Manhattan  
4998     yes  Midtown West       All Midtown  Manhattan  
4999     yes       Tribeca      All Downtown  Manhattan